### ISSUE TITLE
WordCount doesn't appear

### ISSUE THREAD

**Issue by ghost** [titoBouzout/WordCount#53]
Just that, the only thing it does is creating an entry in Prefferences>Package Settings. There isn't anything in the command palete or status bar.
![screenshot 544](https://cloud.githubusercontent.com/assets/13372971/14160434/bfbb3758-f6b2-11e5-81e3-6f4b541690a8.png)

**Comment by anders-s** [comment]
Same issue.

**Comment by tomakita** [comment]
I'm having the same issue.  Perhaps I've done something wrong during the install?

**Comment by excetara2** [comment]
Same issue.

**Comment by ghost** [comment]
I tried installing again, this time it worked. I dunno why really, last time I also had followed the same method-- download as zip, rename main folder to WordCount, extract to /packages/.
Maybe there was an unmet dependency? What exactly does this plugin need to work?
  ----- Original Message -----

**Comment by excetara2** [comment]
I had to reboot sublime and it started working for me as well.

**Comment by tomakita** [comment]
Re-installing also worked for me (I had tried restarting Sublime before, but that didn't seem to fix the problem, in my case).  Thanks for the tip!

**Comment by kylemcdonald** [comment]
I have the same issue. Opening the Sublime console reveals:

``` python
Reloading plugin /Users/kyle/Library/Application Support/Sublime Text 2/Packages/WordCount/WordCount.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./WordCount.py", line 282
SyntaxError: Non-ASCII character '\xe2' in file ./WordCount.py on line 282, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

This is due to the character added in this commit https://github.com/titoBouzout/WordCount/commit/a8c94527fdba12d83596d2b1c0f26f719db5cb3f

Adding the line `# -*- coding: utf-8 -*-` to the top of the `WordCount.py` file fixes this error.

I still don't see a word count displayed anywhere.

**Comment by Awatatah** [comment]
I'm having the same issue as @kylemcdonald  please fix!

**Comment by stormtek** [comment]
I just managed to install this on Windows 10. It wanted the folder to be placed in User_Directory/AppData/Roaming/SublimeText3/Packages rather than ProgramFiles/SublimeText3/Packages.

**Comment by KingsleyG** [comment]
I had this issue when I installed WordCount with ST2 - works fine with ST3.

**Comment by kewp** [comment]
Same problem
