### ISSUE TITLE
ws['modified'] = True -> TypeError

### ISSUE THREAD

**Issue by reagle** [titoBouzout/WordCount#62]
I've had this error for a long time. I haven't bothered to do anything because wordcount seems to work but I now wonder if it's causing problems for other plugins.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 577, in on_modified_async
    callback.on_modified_async(v)
  File "/Users/reagle/Library/Application Support/Sublime Text 3/Packages/WordCount/WordCount.py", line 93, in on_modified_async
    ws['modified'] = True
TypeError: 'NoneType' object does not support item assignment
```

**Comment by maxim** [comment]
Would love to see this fixed as well. I'm not a python dev, but feels like it might be a tiny fix. 🤔
